note_keeper/backup/urls.py
from django.urls import path

from . import views

app_name = 'note_keeper'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create_note/', views.create_note, name='create_note'),
    path('<str:note_title>/delete_note/', views.delete_note, name='delete_note'),
    path('<str:pk>/', views.DetailView.as_view(), name='note'),
    path('<str:pk>/edit', views.EditView.as_view(), name='edit_note'),
    path('update_note', views.update_note, name='update_note')
]

note_keeper/urls.py
from django.urls import path

from . import views

app_name = 'note_keeper'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create_note/', views.create_note, name='create_note'),
    path('<str:note_title>/delete_note/', views.delete_note, name='delete_note'),
    path('<str:pk>/', views.DetailView.as_view(), name='note'),
    path('<str:pk>/edit', views.EditView.as_view(), name='edit_note'),
    path('update_note', views.update_note, name='update_note')
]

notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('note_keeper/', include('note_keeper.urls'))
]

note_keeper/backup/models.py
from django.db import models
from django.utils import timezone
import datetime

class Note(models.Model):
    title = models.CharField(max_length=200, primary_key=True)
    content = models.TextField()
    now = timezone.now()
    doc = models.DateTimeField('date published', default=now)
    modify_date = models.DateTimeField('date published', default=now)

    def __str__(self):
        return "Title: {} \nContent: {} \nDate of Creation: {} \nLast modify: {}".format(self.title, self.content, self.doc, self.modify_date) 

note_keeper/models.py
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
    title = models.CharField(max_length=200, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    modify_date = models.DateTimeField('date published', auto_now_add=True)
    doc = models.DateTimeField('date published', auto_now_add=True)
 

    def __str__(self):
        return "Title: {} \nContent: {} \nDate of Creation: {} \nLast modify: {}".format(self.title, self.content, self.doc, self.modify_date) 

note_keeper/backup/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Note
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class IndexView(generic.ListView):
 #   login_url = '/accounts/login'
    template_name = 'note_keeper/index.html'
    context_object_name = 'latest_note_list'

    def get_queryset(self):
        """Return the last five published Note."""
        return Note.objects.order_by('-modify_date')[:3]
      #  return Note.objects.filter(modify_date__lte=timezone.now()).order_by('-modify_date')[:]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['all_note'] = Note.objects.all()
        return context

class DetailView(generic.DetailView):
    model = Note
    template_name = 'note_keeper/note.html'

class EditView(generic.DetailView):
    model = Note
    template_name = 'note_keeper/edit_note.html'
    
def delete_note(request, note_title):
    messages.info(request, 'Note title #{} has been deleted'.format(note_title))
    Note.objects.filter(pk=note_title).delete()
    return HttpResponseRedirect(reverse('note_keeper:index'))

def create_note(request):
    title = request.POST['title']
    content = request.POST['content']
    for note in Note.objects.all():
        if note.title == title:
            messages.info(request, "Title is taken, please use different one!")
            return HttpResponseRedirect(reverse('note_keeper:index'))

    note = Note(title=title, content=content)
    note.save()
    messages.info(request, 'Note: {} has been saved'.format(title))
    return HttpResponseRedirect(reverse('note_keeper:index'))

def update_note(request):
    title = request.POST['title']
    content = request.POST['content']
    curr_title = request.POST['old_title']
    note = Note.objects.get(pk=curr_title)
    if note.title != title: 
        for db_note in Note.objects.all():
            if db_note.title == title:
                messages.info(request, "Title is taken, please use different one!")
                return HttpResponseRedirect(reverse('note_keeper:note', args=[curr_title])) 
        new_note = Note(title=title, content=content,doc=note.doc)  
        Note.objects.filter(pk=note.title).delete()
        new_note.save()
    elif note.title == title and note.content == content:
         messages.info(request, "No change detected")
    else:
        note.modify_date = timezone.now()
        note.title = title
        note.content = content 
        note.save()
        messages.info(request, 'Note #{} has been updated'.format(title))
    return HttpResponseRedirect(reverse('note_keeper:note', args=[title]))

note_keeper/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from .models import Note
from django.utils import timezone
from django.contrib import messages
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/accounts/login/'
    template_name = 'note_keeper/index.html'
    context_object_name = 'latest_note_list'

    def get_queryset(self):
        """Return the last five published Note."""
        return Note.objects.filter(user=self.request.user).filter(modify_date__lte=timezone.now()).order_by('-modify_date')[:3]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['all_note'] = Note.objects.filter(user=self.request.user).all()
        return context

class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = '/accounts/login/'
    model = Note
    template_name = 'note_keeper/note.html'

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
            if self.object.user != self.request.user:
                raise Http404
        except Http404:
            messages.info(request, "There is no such note in your account")
            return HttpResponseRedirect(reverse('note_keeper:index'))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

class EditView(LoginRequiredMixin, generic.DetailView):
    login_url = '/accounts/login/'
    model = Note
    template_name = 'note_keeper/edit_note.html'

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
            if self.object.user != self.request.user:
                raise Http404
        except Http404:
            messages.info(request, "There is no such note in your account")
            return HttpResponseRedirect(reverse('note_keeper:index'))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


def delete_note(request, note_title):
    if Note.objects.filter(pk=note_title).exists(): 
        note = Note.objects.get(pk=note_title)
        if note.user != request.user:
            messages.info(request, 'You cannot delete other people note')
            return HttpResponseRedirect(reverse('note_keeper:index'))
        if not request.user.has_perm('note_keeper.delete_note'):
            messages.info(request, 'No permission to delete')
            return HttpResponseRedirect(reverse('note_keeper:index'))
        messages.info(request, 'Note title #{} has been deleted'.format(note_title))
        Note.objects.filter(pk=note_title).delete()
        return HttpResponseRedirect(reverse('note_keeper:index'))
    messages.info(request, 'Note title {} is not existed'.format(note_title))
    return HttpResponseRedirect(reverse('note_keeper:index'))


def create_note(request):
    user = request.user
    title = request.POST['title']
    content = request.POST['content']
    if not len(title) or not len(content):
        messages.info(request, "Title or Content is empty, please write the form again")
        return HttpResponseRedirect(reverse('note_keeper:index'))

    if Note.objects.filter(pk=title).exists():
        messages.info(request, 'Title is taken, remove the previous note first!')
        return HttpResponseRedirect(reverse('note_keeper:index'))
    note = Note.objects.create(user=user, title=title, content=content) 
    note.save()
    messages.info(request, 'Note: {} has been saved'.format(title))
    return HttpResponseRedirect(reverse('note_keeper:index'))

def update_note(request):
    title = request.POST['title']
    content = request.POST['content']
    curr_title = request.POST['old_title']
    if len(title) < 3:
        messages.info(request, "Please enter the title at least 3 characters or above")
        return HttpResponseRedirect(reverse('note_keeper:index'))
    if not Note.objects.filter(pk=curr_title).exists():
        messages.info(request, "Sorry, I cannot let you do this")
        return HttpResponseRedirect(reverse('note_keeper:index'))
    note = Note.objects.get(pk=curr_title)

    if note.title == title and note.content == content:
        messages.info(request, "No change detected")
        # return redirect(request.META['HTTP_REFERER'])
        return HttpResponseRedirect(reverse('note_keeper:index'))
        
    if note.title != title: 
        if Note.objects.filter(pk=title):
            messages.info(request, "Title is already taken! use different one.")
            return redirect(request.META['HTTP_REFERER'])
        new_note = Note(title=title, content=content,doc=note.doc, modify_date=timezone.now())  
        Note.objects.filter(pk=note.title).delete()
        new_note.save()
        return HttpResponseRedirect(reverse('note_keeper:index'))
    
    if note.title == title and note.content != content:
        note.modify_date = timezone.now()
        note.title = title
        note.content = content 
        note.save()
    messages.info(request, 'Note #{} has been updated'.format(title))
    return HttpResponseRedirect(reverse('note_keeper:note', args=[title]))

note_keeper/templates/note_keeper/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'note_keeper/style.css' %}"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Note Keeper | {% block title %} Index {% endblock %}</title>
  </head>
  <body>
   <section>
   {% comment %} Header {% endcomment %}
   <div class="margin-bot">
    <p class="text-grey" style="float: left">  {% block currPage %} Index {% endblock%}</p>
	<p style="float: right">Welcome <span class="text-gray"> {{ request.user.username }} </span> | <a href="{% url 'logout' %}" class="text-danger"> Log out </a> </p>
   </div>
	<div class="align-center">
    <img class="margin-bot" src="{% static 'note_keeper/images/note.svg' %}" height="250 px" width="250 px">
    <h1>{% block heading1 %} Note Keeper {% endblock %} </h1>
	</div>
	</section>

	<section>
	{% comment %} Body {% endcomment %}
  {% block alert %} 	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<div class="position-fixed bg-white border font-weight-bold border-dark alert alert-white alert-dismissible fade show" style="top: 10px; right: 1vw;" role="alert">
			{{ message }}
			<a type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
			</a>
		</div>
		
		{% endfor %}
	</ul>
	{% endif %}
	
  {% endblock %}
    {% block mainbody %} {% endblock %}
  </section>
	<section class="margin-top">
	{% comment %} Footer {% endcomment %}
      <hr>
      <div class="align-center">
        <p><address>Made by <br /> Chan Broset</address></p>
      </div>
    </section>
 
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 </body>
</html>

note_keeper/templates/note_keeper/edit_note.html
{% extends "note_keeper/base.html" %}
{% block title %} Editing #{{ note.title }} {% endblock %}
{% block currPage %} <a href="{% url 'note_keeper:index' %}"> Index </a> > Editing {{ note.title }} {% endblock %}
{% block heading1 %} Editing Mode On {% endblock %}

{% block mainbody %} 

<hr />
<p class="text-center">Editing <span class="text-muted">{{ note.title }}</span> </p>
<div class="container">

<div class="row">
  <div class="col my-1">
    <h2> Previously: </h2>
      <label for="title">Title:</label>
      <input disabled="true" value="{{ note.title }}" type="text" class="form-control" id="title" name="title" placeholder="title">
        <label for="content">Content: </label>
        <textarea disabled="true" required="required" class="form-control" id="content" name="content" rows="20">{{ note.content }} </textarea>
 
  </div>

  <div class="col my-1">
  <form action="{% url 'note_keeper:update_note' %}" method="post">
  {% csrf_token %}
  <h2> Currently: </h2>
   <label for="title">Title:</label>
    <input value="{{ note.title }}" required="required"  type="text" class="form-control" id="title" name="title" >
  <label for="content">Content: </label>
    <textarea required="required" class="form-control" id="content" name="content" rows="20">{{ note.content }}</textarea>
    <input type="hidden" name="old_title" value="{{ note.title }}">
    <div style="text-align: right">
  
  <a href="{% url 'note_keeper:note' note.title %}" class="btn btn-secondary my-1"> Cancel </a>
    <input value="Update" type="submit" class="btn btn-danger my-1 align-right">
    </div>
    </form>
  <div>
</div>





</div>
{% endblock %}


</div>

note_keeper/templates/note_keeper/index.html
{% extends "note_keeper/base.html" %}

{% block mainbody %}
	<h2 class="margin-top">Recent Notes: </h2>
	<hr />

	 {% if latest_note_list %}
		<div class="flex-container" style="justify-content: center">
		
		{% for note in latest_note_list %}
	
			<div class="flex-item mx-4 m-1" style="height: 250px">
				<div class="card" style="width: 18rem; height: 15rem">
					<div class="card-body">
						<h5 class="card-title"><a href="{% url 'note_keeper:note' note.title %}">
						{{ note.title }}</a></h5>
						<h6 class="card-subtitle mb-2 text-muted"> {{ note.doc }} </h6>
						<p class="card-text">{{ note.content | truncatewords:10 }} </p>
					</div>
					
					<div class="my-1 mx-2 justify-content-end">
					<div class="text-right">
					<span class="text-muted">
						{% if note.modify_date > note.doc %} {{ note.modify_date }} {% else %} No changes {% endif %}
					</span>
						<a href="{% url 'note_keeper:delete_note' note.title %}" class="text-danger card-link text-right">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
							<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
							<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
							</svg>
						</a>
					</div>
					</div>

						
					
				</div>
			</div>
		{% endfor %}
		</div>
	{% else %}
	<ul>
		<p> Your notebook is empty right now!
		</p>
	</ul>
	{% endif %}

 <h2> Add Note: </h2>
<hr />

<form action="{% url 'note_keeper:create_note' %}" method="post">
{% csrf_token %}
 <div class="form-group">
    <label for="title">Title:</label>
    <input required="required" type="text" class="form-control" id="title" name="title" placeholder="Title">
  </div>
  <div class="form-group">
    <label for="content">Content: </label>
    <textarea required="required" class="form-control" id="content" name="content" rows="8"></textarea>
  </div>
  <button class="my-1 btn btn-outline-primary float-right" type="submit">
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-save2" viewBox="0 0 16 16">
  <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
</svg>
Save 
</button>
</form>


	<h2 class="margin-top"> List of notes </h2>
	<hr />
	<ul>
		{% for note in all_note %}
		<li><a href="{% url 'note_keeper:note' note.title %}"> {{ note.title }} </a></li>
		{% empty %}
		 Your notebook is empty right now!
		{% endfor %}
	</ul>



{% endblock %}

{% block goback %}
{% endblock %}

note_keeper/templates/note_keeper/note.html
{% extends "note_keeper/base.html" %}
{% block title %} {{ note.title }} {% endblock %}
{% block currPage %} <a href="{% url 'note_keeper:index' %}"> Index </a> > {{ note.title }} {% endblock %}
{% block heading1 %} {{ note.title }} {% endblock %}

{% block mainbody %} 
<hr />
<p class="text-center"> {% if note.doc >  note.modify_date %} Created: {{ note.doc }} {% endif %} 
{% if note.modify_date > note.doc %} Created: {{ note.doc }}, Updated: {{ note.modify_date }} {% endif %} </p>

<p> {{ note.content | linebreaks }} </p>


<div class="margin-top">
<a href="{% url 'note_keeper:index' %}"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="30" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
</svg> Return </a> 
 | 
  <a href="{% url 'note_keeper:edit_note' note.title %}" class="card-link text-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
  <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
</svg> Edit</a> 

</div>
{% endblock %}